feat: histories api 명세 작성
jiphyeonjeon-42/backend-nest pull request #48
Opened 2024-09-19 08:42 UTC by nyj001012

2024-09-19 12:43 UTC, scarf005 requested changes
`nestjs-zod`에서 `@anatine/zod-nestjs`로 전환이 필요할 것 같습니다.

2024-09-19 12:43 UTC, scarf005 commented on backend/src/histories/schema/histories.schema.ts
> +import { z } from 'nestjs-zod/z';
```suggestion
import { z } from 'zod';
```

2024-09-19 12:43 UTC, scarf005 commented on backend/src/histories/dto/histories.dto.ts
> +import { createZodDto } from 'nestjs-zod';
```suggestion
import { createZodDto } from '@anatine/zod-nestjs';
```

2024-09-20 12:17 UTC, jimin52 approved these changes

2024-09-28 01:51 UTC, merged